# Generated by Django 4.2.4 on 2023-09-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(null=True, upload_to='media/account', verbose_name='user profile'),
        ),
    ]
