# Generated by Django 4.2.4 on 2023-08-22 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodels',
            name='have_children',
            field=models.BooleanField(default=False, verbose_name='category is parent of another category'),
        ),
        migrations.AlterField(
            model_name='categorymodels',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.categorymodels', verbose_name='category parend'),
        ),
    ]
