# Generated by Django 4.2.4 on 2023-08-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_categorymodels_have_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='have_reply',
            field=models.BooleanField(default=False, verbose_name='This comment have reply/replies'),
        ),
    ]
