# Generated by Django 4.2.4 on 2023-09-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_like_count_comment_parent_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to='media/blog/articles', verbose_name='blog image'),
        ),
        migrations.AlterField(
            model_name='categorymodels',
            name='image',
            field=models.ImageField(upload_to='media/blog/categorys', verbose_name='category image'),
        ),
    ]
