# Generated by Django 4.2.4 on 2023-09-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogmodel_image_alter_categorymodels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodels',
            name='image',
            field=models.ImageField(default=None, upload_to='media/blog/categorys', verbose_name='category image'),
        ),
    ]
